name: checkin
on:
  schedule:
    - cron: "45 02 * * *"
  workflow_dispatch:
    inputs:
      logLevel:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: auto checkin for traffic

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: checkin
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
      - run: |
          pip install -U requests
          pip install simplejson
          echo ${{secrets.AP_CONFIG}} | base64 --decode > config.json
          python auto-checkin.py

      - name: timestamp
        run: date
